name: Build
on:
  push:
    branches:
      - main
 
jobs:
  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    container: lorisleiva/laravel-docker:7.4
    steps:
      - uses: actions/checkout@v2
      - run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - run: ./vendor/bin/phpcs --standard=./phpcs.xml --extensions=php app --warning-severity=0
      - run: npm ci
      - run: npm run dev
      - name: Configure application
        run: |
          cp .env.ci .env
          php artisan cache:clear
          php artisan config:clear
          php artisan key:generate
      - run: ./vendor/bin/phpunit --colors=never
 
  deploy:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging'
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [build-php]
    env:
      VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
      VAPOR_ENV: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
    steps:
      - uses: actions/checkout@v2
      - run: composer install --no-dev --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - run: ./vendor/bin/vapor deploy ${{ env.VAPOR_ENV }}